version: 2
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: gradle lintKotlin test jacocoTestReport
      - codecov/upload:
        file: build/reports/jacoco/test/jacocoTestReport.xml
workflows: 
  version: 2
  continuous:
    jobs:
      - test
