version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: gradle test
workflows: 
  version: 2
  continuous:
    jobs:
      - test